### ISSUE TITLE
German Text:  Fehlermeldung 

### ISSUE THREAD

**Issue by Schuberth1980** [trinko/contao-zad_docman#1]
Sehr geehrte Damen und Herren,

ich habe auf meinem Lokalen Mac Contao 3.4 installiert und wollte gerne  das ZAD Docman ausprobieren. Die Installation scheint zu klappen, aber weiter  ging es trotzdem nicht. Denn als ich ein Documentar Manager anlegen wollte kommt folgender Fehlerhinweis:

das ich in der error.log nach schauen soll. In dieser Stand folgendes drin:

[28-Mar-2015 21:23:35 Europe/Berlin] PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: Column 'name' cannot be null (INSERT INTO tl_zad_docman_templates (pid, tstamp, name, text) VALUES ('1', 1427574215, NULL, NULL))' thrown in /Applications/MAMP/htdocs/um-welt.info/contao/system/modules/core/library/Contao/Database/Statement.php on line 293
#0 /Applications/MAMP/htdocs/um-welt.info/contao/system/modules/core/library/Contao/Database/Statement.php(262): Contao\Database\Statement->query()
#1 /Applications/MAMP/htdocs/um-welt.info/contao/system/modules/zad_docman/dca/tl_zad_docman_archive.php(322): Contao\Database\Statement->execute()
#2 /Applications/MAMP/htdocs/um-welt.info/contao/system/modules/core/drivers/DC_Table.php(199): tl_zad_docman_archive->generateTemplate(Object(Contao\DC_Table))
#3 /Applications/MAMP/htdocs/um-welt.info/contao/system/modules/core/classes/Backend.php(393): Contao\DC_Table->__construct('tl_zad_docman_a...', Array)
#4 /Applications/MAMP/htdocs/um-welt.info/contao/system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('zad_docman')
#5 /Applications/MAMP/htdocs/um-welt.info/contao/contao/main.php(20): Contao\BackendMain->run()
#6 {main}

Weshalb funktioniert das Modul nicht ?
Ich bitte um eine  Antwort, vielen Dank.

Mit freundlichen Grüßen
Thomas Schuberth

**Comment by trinko** [comment]
Sorry, I don't speak German.
Anyway, as you posted the error log I understood the problem. I'll fix it soon in next release.
Thanks.

**Comment by trinko** [comment]
I fixed this bug.
You can install new version 0.9.2 beta1 from Contao repository:
https://contao.org/en/extension-list/view/zad_docman.90023.en.html
